### ISSUE TITLE
Retrieve Private Repository

### ISSUE THREAD

**Issue by sparkline-charlie** [lipis/github-stats#2]
Hi @lipis ,

Thanks for this informative application you've created. Just want to ask this following questions
1. What additional package or method you used in order to retrieve data in github?
2. How to retrieve private repository

**Comment by lipis** [comment]
1. Not much besides the [PyGitHub](https://github.com/lipis/github-stats/blob/master/requirements.txt#L7) and to get the latest projects via a cron job the [public API](https://github.com/lipis/github-stats/blob/master/main/control/gh.py#L74)
2. If you just do the example you'll get the private repos as well: https://pypi.python.org/pypi/PyGithub (but you can get the private repos obviously if you will authenticate with that user).
